### ISSUE TITLE
Failing 2 tests when you deploy to production

### ISSUE THREAD

**Issue by liuxiachanghong** [tsalb/lwc-utils#110]
Deploying to sandbox/scratch org works but not to production. I ran the following command line to deploy to production.
`sfdx force:source:deploy -l RunLocalTests -u masahiro@yourdomain.com -p utils-core`

It returns 2 failing Tests but not sure what or where to rectify.

<img width="913" alt="failing-2-test" src="https://user-images.githubusercontent.com/3022694/134460122-968710b6-bfc8-42ac-bd08-35adb44e2577.png">

Pretty cool components, would save a lot of my time.

**Comment by liuxiachanghong** [comment]
Sorry, this worked.(limit to ApexTest)
`-l RunSpecifiedTests -r CalculateFormulasTests,DataTableServiceTests,LookupAuraServiceTests`

**Comment by tsalb** [comment]
Glad you figured it out!

I was going to recommend you install the 2GP modules instead, but that is entirely up to you.
