### ISSUE TITLE
Question : Best way to implement in actual SFDX project ?

### ISSUE THREAD

**Issue by Esya** [tsalb/lwc-utils#15]
Hi, first of all, thanks for this wonderful library !

We've played with it in a scratch org, and are now looking at the cleanest way to use it within our SFDX packages.

What would you recommend as the best way to use it while : 

- Not deploying all of the examples
- Still being able to pull your upstream changes

Would you recommend cloning `force-app/main/default` in our SFDX repository (Maybe as a git submodule) as a separate package, but adding manually everything that is an example to the `.forceignore` file ? Or would you have another cleaner way to do so in mind ?

Thanks a lot !

**Comment by Esya** [comment]
Following up on my previous comment, I managed to do it somewhat cleanly, happy to hear your thoughts, the steps are below

## 1. Add `lwc-utils` as a Git submodule : 

This will create a `utils/lwc-utils` folder at the root of the sfdx project. 

```
$ git submodule add https://github.com/tsalb/lwc-utils utils/lwc-utils
```

## 2. Register the new package directory 

Edit the `sfdx-project.json` and add an entry to `packageDirectories`  pointing to the submodule

```json
{
  "packageDirectories": [
    {
      "path": "force-app",
      "default": true
    },
    {
      "path": "utils/lwc-utils/force-app"
    }
  ],
  // ...
}
```

## 3. Exclude LWC Utils Examples from push using `.forceignore`

Append the following snippet to your `.forceignore` : 

```
# LWC Utils Example Files that need to be ignored
utils/lwc-utils/force-app/main/default/applications
utils/lwc-utils/force-app/main/default/customMetadata
utils/lwc-utils/force-app/main/default/flexipages
utils/lwc-utils/force-app/main/default/flows
utils/lwc-utils/force-app/main/default/lwc/*Example
utils/lwc-utils/force-app/main/default/lwc/lwc*
utils/lwc-utils/force-app/main/default/objects/Account
utils/lwc-utils/force-app/main/default/objects/Contact
utils/lwc-utils/force-app/main/default/tabs
utils/lwc-utils/force-app/main/default/profiles
```

## 4. Caveats

`profiles/Admin.profile` mentions a field created for an example (Contact.Account_Information) so it needs to be ignored, but it's content needs to be reflected into your default org.

**Comment by tsalb** [comment]
Appreciate the kind words!

I have intentionally left out the ability to easily move components to a production environment since this is currently in beta. While I am not opposed to a submodule, I was recently inspired by how rflib handles its [packaging as shown here](https://github.com/j-fischer/rflib/blob/master/sfdx-project.json).

I believe restructuring the project root once I move out of beta and producing a base `core` and `with-example` unlocked packages should help. ETA should be sometime in SEP hopefully (currently backed up with full time work).

Thoughts?

**Comment by Esya** [comment]
That sounds perfectly fine! We will proceed this way for the time being. Looking forward to the production release!
