### ISSUE TITLE
SOQL Datatable - When it doesn't fit on screen, need to scroll down to see the Save button

### ISSUE THREAD

**Issue by solo-1234** [tsalb/lwc-utils#22]
When displaying data which doesn't fit on the screen, you need to scroll to the bottom to see the Save and Cancel buttons. This is a little confusing and also annoying. Can that be fixed?

**Comment by tsalb** [comment]
Unfortunately this is a limitation with regards to how the standard SLDS works.

I would recommend using the `Limit Height (Relative to screen)` option in the app config.

This option is not yet available in Screen Flows, but you can submit a Enhancement request for that!

**Comment by solo-1234** [comment]
Limiting height to 60% of the screen does fix that, but it also wastes a lot of space at the bottom. Could that percent  be customizable? Why 60% anyways?

**Comment by tsalb** [comment]
60% is my preference for a full page table (reserves space at top and bottom for the navigation and utility bar).

Feel free to submit an enhancement for this feature!

**Comment by solo-1234** [comment]
Will do!
