### ISSUE TITLE
SOQL Datatable - Lookup Fields - Sometimes searching doesn't show any results when it should

### ISSUE THREAD

**Issue by solo-1234** [tsalb/lwc-utils#23]
I've noticed this on and off and haven't yet pinpointed the problem. Sometimes when searching to edit a lookup field, no results are shown even though they exist (nor does the toast that says no results display). Refreshing the page seems to fix it.

**Comment by solo-1234** [comment]
I wonder if this is a CPU or RAM issue, I am noticing that some of the lookup fields show Undefined when this happens, and it may be when my CPU/RAM utilization is high.

**Comment by tsalb** [comment]
Closing as I can't repro - if you see this again would love to hear exact repro steps!

**Comment by solo-1234** [comment]
Hmm, I don't remember where it was! Let's see if it comes up again. TY
