### ISSUE TITLE
SOQL Datatable - Row numbers only work until 99?

### ISSUE THREAD

**Issue by solo-1234** [tsalb/lwc-utils#27]
in soqldatatable, it looks like row numbers only display until the 99th record.

screenshot: https://i.imgur.com/8HqsRrh.png

**Comment by tsalb** [comment]
Confirmed this is a base component bug. `lightning-datatable` will happily show row numbers _without_ the `show-row-number-columns` property up to 99, but require it after 99?

How weird.

So then, the fix will be to dynamically add this prop as necessary. I attempted `show-row-number-columns="false"` and that doesn't work, so I will need to add the prop from `datatable.js` to `lightning-datatable` ad-hoc.
