### ISSUE TITLE
Aggregate Queries in SOQL Datatable - Add README documentation

### ISSUE THREAD

**Issue by tsalb** [tsalb/lwc-utils#29]
https://github.com/tsalb/lwc-utils/pull/24 is a really neat feature I'd love to have documented, we should get the README updated with some usage steps and instructions for all to see.

Not that important yet to create a PR for it, but we can use this thread to dump pictures and hash out what kind of examples to show users this is now possible (and any limitations should be called out as well).

FYI @jamessimone

**Comment by jamessimone** [comment]
Limitation:

- `count()` is not supported, as it alone among the aggregate queries does not return a `List<SObject>` but an integer.
- `LIMIT` is not supported in queries using an aggregate function without a `GROUP BY` clause. We could snip a user-submitted `LIMIT` argument off the end of the query-string, but that would be a future enhancement (and has the downside of invisibly fixing an invalid SOQL statement).
