### ISSUE TITLE
SOQL Datatable - ability to have more than 2 table actions

### ISSUE THREAD

**Issue by solo-1234** [tsalb/lwc-utils#38]
It would be great to have more than 2 table actions at the top of a datatable

**Comment by tsalb** [comment]
Super future enhancement, this requires figuring out how to slot n-buttons and also add overflow (like the regular dynamic actions in App Builder now).

Would be a breaking change, so `2.0.0` aspirations. No roadmap there yet!

**Comment by solo-1234** [comment]
Sounds good

**Comment by tsalb** [comment]
As part of #54, and my desire to reuse the `SOQL Datatable` tab in the recipes to introduce a 3rd flow to debug #54...

I've started down this path toward a new (intermediary) datamodel that both adds `Table Overflow Actions` as well as better addresses ambiguity in #37.

New Improved Layout, for #37:
<img width="870" alt="Screen Shot 2021-01-18 at 7 20 32 PM" src="https://user-images.githubusercontent.com/32919768/104983799-58023800-59c2-11eb-9e99-b487a27592fb.png">

New `Type__c` values for new `Datatable_Action_Config__mdt` rows (backwards compat with existing configs):
<img width="1082" alt="Screen Shot 2021-01-18 at 7 23 36 PM" src="https://user-images.githubusercontent.com/32919768/104984036-d7900700-59c2-11eb-843d-abf9be7428d2.png">

And finally, an overview of what `Datatable_Action_Config__mdt` would look like **using all new config**:
<img width="1169" alt="Screen Shot 2021-01-18 at 7 28 37 PM" src="https://user-images.githubusercontent.com/32919768/104984351-66048880-59c3-11eb-9bda-6a287407828c.png">

**Comment by tsalb** [comment]
Clarification on screenshot above - I could not deprecate existing picklist values so I added an `(OLD)` label suffix to them.
