### ISSUE TITLE
SOQL Datatable - Screen flows should close when you click Finish

### ISSUE THREAD

**Issue by solo-1234** [tsalb/lwc-utils#39]
As of now, if you run a flow from a button, when you click Finish, it restarts from the beginning of the flow. You need to use DialogAutoCloser in your screen (and probably hide the Finish button) to get the modal to close. It would be nice to have the option for Finish to close the modal, since that's how flows work elsewhere in SF.

**Comment by tsalb** [comment]
This is a good point but a design decision that I have decided to do nothing different than what Flows do normally.

You can think of it like this:

SOQL Datatable => Launch Flow in Dialog => END

From the perspective of the SOQL Datatable LWC, its job is done and it has successfully opened a Screen Flow in a modal. You as the solution designer are now fully in charge of the finish behavior (including the fact the Finish button on a standard Screen Flow restarts it, just like when you embed screen flows onto Record Pages).

So then, you can define what happens at the end - including using `DialogAutoCloser` with very little wait time OR you can extend that code (copy paste) to create a Aura component flow action that immediately closes the dialog!

**Comment by solo-1234** [comment]
So I guess I'm thinking of more how a flow works when you launch it from an Action button on a record page - runs until you click Finish, and then the modal closes. I don't know how the back end of flows work in terms of the modal closing, but it would be nice if we could mimic that.
