### ISSUE TITLE
SOQL Datatable - Error on load in record flexipage

### ISSUE THREAD

**Issue by danifin** [tsalb/lwc-utils#44]
when try to load record page getting this error
![image](https://user-images.githubusercontent.com/11889027/102194999-ae152480-3ec6-11eb-8541-9445977a2336.png)

**Comment by tsalb** [comment]
Thanks @danifin for logging an issue - I'm not able to repro from a fresh scratch org using `1.1.1`.

Do you have more details such as:
- Is this installed in sandbox?
- Can you provide the `queryString`?
    - Follow up: how many rows of data?
    - If you're comfortable with code, you can uncomment some `console.log` to see what data the server is returning with (if at all).
- What package version did you install?

Off the top of my head, it might be the scope of data is too large or other error handling not catching bad data before it tries to run the init function.

**Comment by danifin** [comment]
i am in the old version (in sandbox) since i can't install the new one cause i get an error "lwc/datatable/datatable.js-meta.xml: You can’t change the isExposed property to ‘false’ because the component is part of a managed package., Details: datatable: lwc/datatable/datatable.js-meta.xml: You can’t change the isExposed property to ‘false’ because the component is part of a managed package."
i think the reason is we already have another lwc called datatable.

the query when i test it in developer console returns only 2 records as expected.

**Comment by tsalb** [comment]
Closing this out for inactivity, you may be interested in following #47 as that might be on the roadmap
