### ISSUE TITLE
Collection Datatable - Picklist labels don't resolve correctly on inline edit

### ISSUE THREAD

**Issue by Feldstrom** [tsalb/lwc-utils#46]
When displaying a picklist field in the collection datatable, the value of the picklist is not displayed initially. 

When editing the picklist you can select a value, however that value is not shown in the datatable afterwords. 

https://user-images.githubusercontent.com/30249667/103697296-9294bb00-4f54-11eb-9d00-02babe43eaf7.mov

**Comment by tsalb** [comment]
99% sure this is related to this [commit](https://github.com/tsalb/lwc-utils/pull/43/commits/515910ba4b5ddfa7647b4acf7729d4cd16faef38)

Can you do me a favor and give a screenshot of the label / API name of this field (from Object Manager) and also the picklist value label / api name?

**Comment by Feldstrom** [comment]
<img width="918" alt="Screen Shot 2021-01-05 at 1 17 56 PM" src="https://user-images.githubusercontent.com/30249667/103699867-709d3780-4f58-11eb-89d2-85eafac37405.png">
<img width="854" alt="Screen Shot 2021-01-05 at 1 18 15 PM" src="https://user-images.githubusercontent.com/30249667/103699888-78f57280-4f58-11eb-8adf-ba27ac42ac59.png">

**Comment by Feldstrom** [comment]
I installed the package after the v50 bugfix 
<img width="1119" alt="Screen Shot 2021-01-05 at 1 20 05 PM" src="https://user-images.githubusercontent.com/30249667/103700058-ba861d80-4f58-11eb-86e6-25aba80de392.png">

**Comment by tsalb** [comment]
Yeah, sorry - that commit likely introduces the issue - it introduces separate calculation that attempts to resolve picklist api name and values.

This should be enough information for me to repro - I did not test `collectionDatatable` as much as `soqlDatatable` when i introduced that feature.

**Comment by tsalb** [comment]
@Feldstrom interestingly enough, I can't repro this using a fresh scratch org. I'll need some additional details (the more screenshots the better). Please include any relevant ones:

- How you set up the Get Records.
- How you set up the collection to pass into `collectionDatatable`.
- How `collectionDatatable` is configured (all the options on the right).
- Your screen flows elements before/after the `collectionDatatable`.
- Do you have any record types on the object in question?
    - Does said user who is using `collectionDatatable` have access to those record types?

**Comment by tsalb** [comment]
One more data point:

 - If instead of Get Records + `collectionDatatable`, you were able to use `soqlDatatable` to effectively get the same records in view - do you still exhibit the same issue?
     - This data point would help me pinpoint if the problem is somehow isolated to using `collectionDatatable` which is an entirely different problem, since both tables implement their cells in the same way...

**Comment by Feldstrom** [comment]
Getting User records where ManagerId = running user:
<img width="721" alt="Screen Shot 2021-01-05 at 4 28 09 PM" src="https://user-images.githubusercontent.com/30249667/103714223-01810c80-4f73-11eb-8bef-27747ec2c3e3.png">

<img width="629" alt="Screen Shot 2021-01-05 at 4 28 30 PM" src="https://user-images.githubusercontent.com/30249667/103714268-1a89bd80-4f73-11eb-9354-4ea8b92924f5.png">

<img width="631" alt="Screen Shot 2021-01-05 at 4 28 35 PM" src="https://user-images.githubusercontent.com/30249667/103714253-11005580-4f73-11eb-9902-723dd78f550f.png">

- Flow goes Get Records ->Screen with datatable, nothing before that.  
- No record types on User object. 
- I'm the user with full sysadmin in this sandbox and FLS for the field in question.

I can try with the soqlDatatable later on this evening.

**Comment by tsalb** [comment]
I was able to repro with Screen flow using:
- User Get Record (scratch org, all users).
- Adding the same Custom Field (`Manager_Review__c`, two values) on User per your earlier comment.
- Enabling in-line edit on `Manager_Review__c`.

This should get me enough data to figure out whats happening, no ETA on fix.

As an aside, I would be curious to know your outcome on using `soqlDatatable` but that is academic - it shouldn't affect the investigation from this.

**Comment by Feldstrom** [comment]
<img width="1463" alt="Screen Shot 2021-01-05 at 4 56 47 PM" src="https://user-images.githubusercontent.com/30249667/103716128-1c558000-4f77-11eb-9d95-993d038f10aa.png">
