### ISSUE TITLE
Unable to install due to potential name conflicts (lack of namespace)

### ISSUE THREAD

**Issue by RomanTheCube** [tsalb/lwc-utils#47]
Hi folks, just a note to point out that without a namespace there will likely be some conflicts due to naming of various components in this package, (eg: datatable, a super popular component in UnofficialSF's arsenal....). Would be great if a namespace could be added..

**Comment by tsalb** [comment]
Namespacing has definitely been an option, but i'm at a loss on how to ensure backwards compatibility (if any?) or introduce a separate managed package version (with namespace).

Additionally, I have never worked on a managed package so this is out of my depth (and I'm not currently in a place where I can devote bandwidth to figuring out best practices around it).

So then, adding help wanted tag!

**Comment by jamessimone** [comment]
It's possible I'll be able to pick this up in the near future. I have to do the same thing for `Rollup` - in for an inch …

**Comment by tsalb** [comment]
@jamessimone it would be awesome if you just shared a high level strategy too - the implementation is more a side effect.

Since `1.1.1` is out in the wild, we have to assume that current installers need to be given a choice - so my inclination would be to include a separate managed package (installable link) that adds a namespace so users could migrate (if they want).

Or, like @RomanTheCube, net new managed package install to avoid existing conflicts.

Definitely want to learn about what the options (and ramifications) are first!

**Comment by jamessimone** [comment]
@tsalb yeah - I was thinking exactly that (separate managed package that people can use if they want to). There's tradeoffs for unmanaged/managed and having the option for both will give people the tools they need to make that choice.

**Comment by tsalb** [comment]
Based on recent learnings - I think it might be best to add a namespace to an unlocked package.

Previously, I did not know you could do this...

So then, now it’s a question of how best to introduce this into the folder structure / installable url.

Ideally, we give users the option to install:

- Unlocked without namespace (current state)
- Unlocked with namespace (additional option)

Considerations:
- Backwards compatibility with existing (non-namespace) folder structures here - I admit I don’t know how adding one would change the folders and metadata
- Which version would recipes use?
- For users who want to upgrade to the namespaces version, what’s the impact?

**Comment by tsalb** [comment]
It has been brought to my attention by Alex (his team is in charge of Flow) that namespacing in LWC doesn’t work/doesn’t work as expected.

This is a known gap and will be a blocker for this lib.

An alternative is that when I decide to 2.0.0 (breaking change) the lib, I will rename datatable.js to baseDatatable or something more unique.

**Comment by JimBTek** [comment]
If it helps, a collision example error for unofficialSF Datatable v3: 

```
1.  lwc/datatable/datatable.js-meta.xml: This component doesn't support any target for flows, but it's referenced in these flow versions: . Add any of these targets to the component: 'lightning__FlowScreen'.
datatable: lwc/datatable/datatable.js-meta.xml: This component doesn't support any target for flows, but it's referenced in these flow versions: . Add any of these targets to the component: 'lightning__FlowScreen'.

2.  lwc/datatable/datatable.js-meta.xml: You can’t change the isExposed property to ‘false’ because the component is part of a managed package.
datatable: lwc/datatable/datatable.js-meta.xml: You can’t change the isExposed property to ‘false’ because the component is part of a managed package.

3.  lwc/datatable/datatable.js-meta.xml: You can’t remove the following public properties: 
tableData,columnFields,columnAlignments,columnCellAttribs,columnEdits,columnFilters,columnIcons,columnOtherAttribs,columnTypeAttribs,columnWidths,columnWraps,maxNumberOfRows,preSelectedRows,numberOfRowsSelected,isConfigMode,tableHeight,outputSelectedRows,outputSelectedRow,outputEditedRows,tableIcon,tableLabel,isRequired,cb_isRequired,hideCheckboxColumn,cb_hideCheckboxColumn,hideHeaderActions,cb_hideHeaderActions,showRowNumbers,cb_showRowNumbers,singleRowSelection,cb_singleRowSelection,suppressBottomBar,cb_suppressBottomBar,matchCaseOnFilters,cb_matchCaseOnFilters,tableBorder,cb_tableBorder,isDisplayHeader,cb_isDisplayHeader,not_suppressNameFieldLink,cb_not_suppressNameFieldLink,openLinkinSameTab,cb_openLinkinSameTab,suppressNameFieldLink,not_tableBorder,displayAll,cb_displayAll,isUserDefinedObject,cb_isUserDefinedObject,tableDataString,preSelectedRowsString,outputSelectedRowsString,outputEditedRowsString,columnScales,columnTypes,scaleAttrib,typeAttrib,objectName,wizSObject,wizColumnFields,wizColumnAlignments,wizColumnEdits,wizColumnFilters,wizColumnLabels,wizColumnIcons,wizColumnWidths,wizColumnWraps,selectedIcon,scales,types,sortDirection,maxRowSelection,errors,columnWidthValues,lookupId,objectNameLookup,objectLinkField,filterColumns,columnFilterValues,columnType,columnNumber,baseLabel,isFiltered,saveOriginalValue,savePreEditData,editedData,outputData,errorApex,dtableColumnFieldDescriptorString,lookupFieldDataString,basicColumns,lookupFieldArray,columnArray,percentFieldArray,noEditFieldArray,timeFieldArray,picklistFieldArray,picklistReplaceValues,picklistFieldMap,picklistMap,edits,isEditAttribSet,editAttribType,filters,filterAttribType,alignments,cellAttribs,cellAttributes,icons,labels,otherAttribs,typeAttribs,typeAttributes,widths,wraps,lookups,cols,attribCount,recordData,timezoneOffset, because the component is part of a managed package.
datatable: lwc/datatable/datatable.js-meta.xml: You can’t remove the following public properties: tableData,columnFields,columnAlignments,columnCellAttribs,columnEdits,columnFilters,columnIcons,columnOtherAttribs,columnTypeAttribs,columnWidths,columnWraps,maxNumberOfRows,preSelectedRows,numberOfRowsSelected,isConfigMode,tableHeight,outputSelectedRows,outputSelectedRow,outputEditedRows,tableIcon,tableLabel,isRequired,cb_isRequired,hideCheckboxColumn,cb_hideCheckboxColumn,hideHeaderActions,cb_hideHeaderActions,showRowNumbers,cb_showRowNumbers,singleRowSelection,cb_singleRowSelection,suppressBottomBar,cb_suppressBottomBar,matchCaseOnFilters,cb_matchCaseOnFilters,tableBorder,cb_tableBorder,isDisplayHeader,cb_isDisplayHeader,not_suppressNameFieldLink,cb_not_suppressNameFieldLink,openLinkinSameTab,cb_openLinkinSameTab,suppressNameFieldLink,not_tableBorder,displayAll,cb_displayAll,isUserDefinedObject,cb_isUserDefinedObject,tableDataString,preSelectedRowsString,outputSelectedRowsString,outputEditedRowsString,columnScales,columnTypes,scaleAttrib,typeAttrib,objectName,wizSObject,wizColumnFields,wizColumnAlignments,wizColumnEdits,wizColumnFilters,wizColumnLabels,wizColumnIcons,wizColumnWidths,wizColumnWraps,selectedIcon,scales,types,sortDirection,maxRowSelection,errors,columnWidthValues,lookupId,objectNameLookup,objectLinkField,filterColumns,columnFilterValues,columnType,columnNumber,baseLabel,isFiltered,saveOriginalValue,savePreEditData,editedData,outputData,errorApex,dtableColumnFieldDescriptorString,lookupFieldDataString,basicColumns,lookupFieldArray,columnArray,percentFieldArray,noEditFieldArray,timeFieldArray,picklistFieldArray,picklistReplaceValues,picklistFieldMap,picklistMap,edits,isEditAttribSet,editAttribType,filters,filterAttribType,alignments,cellAttribs,cellAttributes,icons,labels,otherAttribs,typeAttribs,typeAttributes,widths,wraps,lookups,cols,attribCount,recordData,timezoneOffset, because the component is part of a managed package.
```


![image](https://user-images.githubusercontent.com/1176347/116619580-a2bf1480-a90e-11eb-9755-6369a9b7aa7a.png)

**Comment by tsalb** [comment]
@JimBTek oh yeah that definitely helps - i've never actually *seen* the error in the wild.

IIRC, the author of that lib was supposed to make their own changes (ahead of mine). I have no ETA on when (or if) I can backwards compatibility a rename.

So, we'll see!

**Comment by JimBTek** [comment]
Seems a little silly to install both in the same org though tbh.  We were just testing different solutions to the same problem.

I don't think there is any good way to change the metadata name of an already deployed asset that is entwined in flows and lightning pages.

**Comment by tsalb** [comment]
@JimBTek 

You’re right it’s hard to unwind. With regards to use case, mine is developer focused and optimized for speed over features. IIRC that other datatable is feature heavy and intended to be used in, primarily, screen flows.

**Comment by solo-1234** [comment]
Considering that each datatable has a small subset of features that the other one doesn't, I can see the advantage of having both available for use as needed. Maybe the unofficialsf one can be replaced with a newer version (not backwards compatible with the current version) which can be installed alongside this one.

**Comment by tsalb** [comment]
@solo-1234

Correct, my understanding is that the other author doesn’t care as much about backwards compatibility and will one day release a v4 (?) that doesn’t conflict with my choice of file naming.

This is low enough on my priority list that I haven’t spent enough time to figure out the feasibility of manual steps required to help people migrate from `datatable.js` to `baseDatatable.js`.

Because I only released unlocked packages, there’s probably some kind of migration guide I could write up to have each org that installed mine first to “unwind” some low level things.

I believe I had the foresight to never expose `datatable.js` to any declarative tool, allowing me to make critical infrastructure decisions like this later on.

However, when, is TBD.

**Comment by solo-1234** [comment]
That makes sense, so I guess we'll see which happens first!

**Comment by ericrsmith35** [comment]
> Correct, my understanding is that the other author doesn’t care as much about backwards compatibility and will one day release a v4 (?) that doesn’t conflict with my choice of file naming.

I am fully aware of maintaining backwards compatibility and make sure that new releases do not change the settings or functionality of existing implementations.

**Comment by tsalb** [comment]
> > Correct, my understanding is that the other author doesn’t care as much about backwards compatibility and will one day release a v4 (?) that doesn’t conflict with my choice of file naming.
> 
> I am fully aware of maintaining backwards compatibility and make sure that new releases do not change the settings or functionality of existing implementations.

@ericrsmith35  I am not sure how that statement aligns to v1, v2, and v3 - My understanding was that you intended to do v4 (or something similar).

Apologies if that expectation was incorrectly aligned but doesn't the fact you are on v3 today leaves some users behind on v1 and v2 without an upgrade path?

**Comment by ericrsmith35** [comment]
Yes, there was a major change when I redid the entire component while switching from Aura to LWC.  My goal has always been that once an attribute is introduced, future releases and new attributes would not change any settings or behavior that a user had implemented in a prior release.

Trying to continue to improve the component while transitioning to Salesforce's moving target of Version 2 packaging has been an ongoing challenge.  There is now a single dev org and packaging environment that should allow a much easier upgrade experience from version to version moving forward.

So yes, upgrading had been an issue with earlier releases but behavior changes should not have been an issue.

**Comment by tsalb** [comment]
Per our discord sync, we've cleared up that the path forward is for me to take the responsibility per this earlier comment:

> figure out the feasibility of manual steps required to help people migrate from `datatable.js` to `baseDatatable.js`.
