### ISSUE TITLE
render() method should return a valid template in flowWizardRouter

### ISSUE THREAD

**Issue by caridy** [tsalb/lwc-utils#5]
Hey James, great stuff. I was looking at the code, and noticed this:

https://github.com/tsalb/lwc-utils/blob/09ceedcd361ed552f7e44e25c9e8c9deb0c1e2cf/force-app/main/default/lwc/flowWizardRouter/flowWizardRouter.js#L24

which returns `null` for some conditions, but that is not longer valid code in later version of LWC.

normally, what you can do now is to have a HTML file with empty template. import it, and return it instead of `null`, that should have the same effect.

**Comment by tsalb** [comment]
Thanks @caridy, I hacked the router together yesterday night and I wasn't quite sure of the behavior of templating when none were desire - but it's good to have confirmation from the source.

Will update accordingly soon.
