### ISSUE TITLE
SOQL Datatable - when passing selected rows from flexipage to flow, include fields on parent objects

### ISSUE THREAD

**Issue by solo-1234** [tsalb/lwc-utils#52]
When a soqldatatable is embedded on a flexipage, with buttons configured to call a flow and pass in the selected records as a collection, it would be useful if the flow could access fields on parent objects.

For example, if a datatable shows a list of Contacts, when passing them to a flow I'd like the flow to be able to access Account fields (the same as if the Contacts were fetched using a Get Records). This way, when looping through the collection of Contacts, I could use something like `{!Loop_thru_Contacts.Account.Website}`.

The same goes for custom objects, let's say my object has a lookup field to Contact, I'd like to use `{!Loop_thru_records.Contact__r.Email}` within a loop.

If it helps performance, I'd be open to specifying in the configuration which lookup fields I'd want to reference that way, so that it doesn't need to include fields from every lookup object on the record.

Let me know if any more details would be helpful. Thank you!

**Comment by tsalb** [comment]
Duplicate
