### ISSUE TITLE
SOQL Datatable: Single quotes in query string not actually escaped

### ISSUE THREAD

**Issue by jamessimone** [tsalb/lwc-utils#55]
It's possible to pass in whatever kind of query string you'd like when using the SOQL datatable, but there is also [a line that would escape quotes from being used](https://github.com/tsalb/lwc-utils/blob/master/utils-core/main/default/classes/DataTableService.cls#L256). Because that value isn't assigned, it's still possible to pass in values with extra dynamism, like in the `test_query_has_advanced_where_filter_should_return_response` test:

```java
String queryString = 'SELECT Name FROM User WHERE Name LIKE \'%BlahBlahBlah%\' LIMIT 1';
```

It wouldn't be possible to do such powerful lookups using SOQL datatable without these previously unescaped strings being supported, but this is also an avenue for potential SOQL injection.

The support for escaped strings should either be documented in the Readme (with the SOQL injection caveat) or the feature could also be removed entirely.

**Comment by tsalb** [comment]
This is muscle memory biting me in the butt - just adding the escape after the fact.

I'd like to remove it (since effectively, if you are passing SOQL in through a public prop, you presumably know what you are doing).

Will take a look!

**Comment by jamessimone** [comment]
Sounds good to me!
