### ISSUE TITLE
SOQL Datatable - close flow modal via action instead of screen component

### ISSUE THREAD

**Issue by solo-1234** [tsalb/lwc-utils#57]
When using a button on SOQL Datatable to run a flow (in a modal), if you want the modal to close when the flow is done, you need to add DialogAutoCloser to the last screen. It would be nice if there was a flow action that could do the same thing, when we don't want to display that component to the user.

TY

**Comment by tsalb** [comment]
Context:

There was a different strategy I used (not in this repo) that deprecates the need for `dialogAutoCloser`.

Note to self: `EventPublisher_LFA`
