### ISSUE TITLE
Feedback on Setup Instructions

### ISSUE THREAD

**Issue by adwhite75** [tsalb/lwc-utils#58]
1. When providing instructions on setting up Flow Variables - make sure you note that the variables must have  'Input' checked.
2. Put in big red letters that Row-actions are not supported in Flow screens.

**Comment by adwhite75** [comment]
I'm also not super clear on where dialogAutoCloser is configured for a given row action.

**Comment by tsalb** [comment]
@adwhite75 feel free to log some more thoughts - at some point, I want to merge these thoughts into #60 

Alternatively, feel free to close this out and migrate the thoughts over to #60

**Comment by tsalb** [comment]
Merged with #60 - please add additional thoughts to that issue

**Comment by adwhite75** [comment]
Looks great thanks!
