### ISSUE TITLE
Slim down README and migrate more information to a WIKI

### ISSUE THREAD

**Issue by solo-1234** [tsalb/lwc-utils#60]
Place your FAQs here!

- My app page datatable has a button that launches a flow. How do I get the modal to go away when the flow is finished?
- I want to call a flow via a button on my flexipage datatable. How do I pass in the selected record(s)?
- In SOQL Datatable in a Flow, what does the 'Record Id' field do?

**Comment by jlyon87** [comment]
Consider a wiki, or even writing a GitHub pages page.

https://guides.github.com/features/wikis/

**Comment by tsalb** [comment]
@jlyon87 Yep, this repo has grown sufficiently feature-rich where a wiki is now the path forward.

To your point, there is a lot of things I should offload to the wiki so the README is more focused.

Let's have this issue be responsible for driving toward that - I'll start organizing once we get sufficient "FAQ" related questions here.

**Comment by tsalb** [comment]
Wiki has been started, this will probably take a few more weekends!

https://github.com/tsalb/lwc-utils/wiki

**Comment by tsalb** [comment]
Migrating from #58 
- When providing instructions on setting up Flow Variables - make sure you note that the variables must have 'Input' checked.
- Put in big red letters that Row-actions are not supported in Flow screens.
- I'm also not super clear on where dialogAutoCloser is configured for a given row action. I think this just needs to mention that it is a screen component and needs to be added to the flow you want autoclosed. Also make note that putting in 0 will auto-close.

**Comment by tsalb** [comment]
https://github.com/tsalb/lwc-utils/wiki

https://github.com/tsalb/lwc-utils/wiki/Getting-Started

https://github.com/tsalb/lwc-utils/wiki/Installation

https://github.com/tsalb/lwc-utils/wiki/Configuration

https://github.com/tsalb/lwc-utils/wiki/FAQ
