### ISSUE TITLE
Collection Datatable - Lookup field names not loading after initialization

### ISSUE THREAD

**Issue by adwhite75** [tsalb/lwc-utils#75]
When using the collection datatable component I noticed that when displaying 'AccountId' from a vanilla Get Records on Contact, it appears as such: 

![image](https://user-images.githubusercontent.com/43993412/108871966-b1fcab80-75c7-11eb-9496-537074621633.png)
![image](https://user-images.githubusercontent.com/43993412/108872024-c17bf480-75c7-11eb-9da5-f2b60c6b75f2.png)

I'm using the latest version of collection datatable.

**Comment by tsalb** [comment]
@adwhite75 you will need to give more repro steps than this, this is working for me using a scratch org with the `master` branch.

One thought here is that your user does not have access to an LDS wire - in which case, I cannot query the account name on your behalf.

Please see the attached working scratch org example image.

<img width="1429" alt="Screen Shot 2021-02-23 at 10 13 08 AM" src="https://user-images.githubusercontent.com/32919768/108888065-dbb1d480-75bf-11eb-81ef-4a39ba278979.png">
