### ISSUE TITLE
SOQL Datatable - "OOTB" edit-row action not properly handling Cancel and Save of datatableEditRowForm

### ISSUE THREAD

**Issue by will-triplemint** [tsalb/lwc-utils#80]
Two issues: When using the edit-row action via custom metadata type within soqlDatatable, the record-form pops up just fine within the modal, however:
* When clicking "Cancel", the modal does not close
* When clicking "Save", an error occurs 
![Lightning_Experience___Salesforce](https://user-images.githubusercontent.com/40894334/111212079-8e64c980-85a5-11eb-860a-a1f3532a3c38.png)

**Comment by tsalb** [comment]
Next action item is on me, thanks for finding my oversight here!

**Comment by tsalb** [comment]
Closed by PR #81
