### ISSUE TITLE
Datatable - Have Search look at Parent Fields

### ISSUE THREAD

**Issue by adwhite75** [tsalb/lwc-utils#82]
I added a parent's custom text field to the datatable but Fuzzy Search doesnt appear to grab it - are parent fields not supported yet?

![image](https://user-images.githubusercontent.com/43993412/113881037-0def4e00-978a-11eb-93f5-1e57479e4941.png)
![image](https://user-images.githubusercontent.com/43993412/113881078-16478900-978a-11eb-918c-694fcc2412a5.png)

**Comment by tsalb** [comment]
Looks like a bug, bandwidth is pretty tied up for the next 30 days or so.

I'll take a look mid-late May!
