### ISSUE TITLE
SOQL Datatable - query/filter for records owned by current user

### ISSUE THREAD

**Issue by solo-1234** [tsalb/lwc-utils#84]
I'd like to configure a datatable (on flexipage) so that it shows each user a list of their records - either via record owner, or via a custom User lookup field. I don't see a way to do that currently.

(Current use case is showing sales reps a dynamic list of calls to make.)

Temporary workaround: create a boolean formula field on the object that compares the running user to the lookup field and filter on that.

Thanks!

**Comment by tsalb** [comment]
I believe I have access to `userId` via some import in LWC (double check later)

Additionally, I think this would align to `$CurrentRecord` API and just use the special string `$CurrentUserId`

**Comment by tsalb** [comment]
Adding some cool context we figured out over the discord.

For this, I'd like to strongly align to what can be leveraged via LDS (read: don't use a custom apex class to back anything related to the `UserInfo` class).

The rationale here is I want to let this framework grow in alignment with LDS (which has some magic built in) and the net benefits of bringing the `UserInfo` class via custom class is, IMO, not worth the investment.

**Comment by jamessimone** [comment]
@tsalb curious on your last comment (since the PR for this uses no Apex class); while LDS isn’t explicitly employed, I suspect the built-in I used leverages it under the hood

**Comment by tsalb** [comment]
@jamessimone oops yes, I haven't checked your PR and that comment was not directed at you (otherwise, it would be on the PR).

That was more additional context when `psb` and my convo on discord reached that conclusion. It was meant for future readers =D

**Comment by jamessimone** [comment]
cheers to posterity!

**Comment by tsalb** [comment]
Closing this, but package has not been made yet.

Keep an eye on the next version when I get to that piece!

**Comment by jamessimone** [comment]
Sounds good - thanks for reviewing!
