### ISSUE TITLE
SOQL Datatable - Allow custom overrides to column definitions to support datatypes to align to native UIs

### ISSUE THREAD

**Issue by JimBTek** [tsalb/lwc-utils#87]
# Problem
Datatable shows 1% as 100%

# In the database:
![image](https://user-images.githubusercontent.com/1176347/116729023-a86f3580-a9b4-11eb-94bc-3ebc472f2951.png)
  
# In standard UI

![image](https://user-images.githubusercontent.com/1176347/116730647-bcb43200-a9b6-11eb-8d96-ca83f05830ba.png)

# in SOQL Datatable
![image](https://user-images.githubusercontent.com/1176347/116729084-bd4bc900-a9b4-11eb-9013-f6cdea2e1de2.png)

in this example the field is listed as editable in the Page config

# Solution

https://developer.salesforce.com/docs/component-library/bundle/lightning-formatted-number/documentation

Specify format-style="percent" to display the value multiplied by 100 as a percent value. Percentages default to 0 decimal places, with rounding. In this example, the formatted number displays as 50%.

```
<template>
    <lightning-formatted-number
            value="0.503"
            format-style="percent">
    </lightning-formatted-number>
</template>
```

To display the value as-is without multiplying it by 100, specify format-style="percent-fixed". In this example, the formatted number displays as 1% because decimal places are not displayed by default and the value is rounded.

```
<template>
  <lightning-formatted-number
            value="0.503"
            format-style="percent-fixed">
  </lightning-formatted-number>
</template>
```

**Comment by tsalb** [comment]
Not sure this is a bug just yet, I aligned the `percent` datatype to whatever OOTB `percent column configs` are given to `lightning-datatable` so this is actually..... a base component (default config?) issue.

More reading and research here: https://developer.salesforce.com/docs/component-library/bundle/lightning-datatable/documentation

See section **Displaying Currency and Percentages**

**Comment by tsalb** [comment]
Additional thoughts here, I might be able to duplicate the `cmdt` config used for **Table Actions / Lookup config** into a generic **Column Config** where you can specify your defaults, overriding whatever `lightning-datatable` does by default.

I think that would be very useful, actually - no ETA on updates (could be a few months at the very least, tbh)
