### ISSUE TITLE
SOQL/Collection Datatable - Add a search function

### ISSUE THREAD

**Issue by solo-1234** [tsalb/lwc-utils#9]
The ability to sort and filter the datatable would be a great addition!

**Comment by tsalb** [comment]
@solo-1234 Sorting is supported, but wasn't documented properly.

This has been added to the [README](https://github.com/tsalb/lwc-utils#soqldatatable---features-and-examples). Both SOQL Datatable and Collection Datatable share the same sorting API.

With regards to filtering, that never be supported (I don't want to recreate the filtering system that's in list views).

That being said, **Global Search** is on my TODO list. I'll recategorize this issue to reflect that.
